language: ruby

rvm:
  - 2.2

cache: bundler
bundler_args: --path ../../vendor/bundle --without debug
gemfile:
  - spec/gemfiles/rails_4_2.gemfile
  - spec/gemfiles/rails_5_0.gemfile

env:
  matrix:
  # Username and password from http://docs.travis-ci.com/user/database-setup/
  - DB=sqlite3
  - DB=mysql2     DB_USERNAME=root     DB_PASSWORD=""
  - DB=postgresql DB_USERNAME=postgres DB_PASSWORD=""
  global:
  # CODECLIMATE_REPO_TOKEN
  - secure: "X+Tmtm+12rDF71aqNzeVRRF5CiiKRaxlKJV0ZJLgWwLHOWX693YGMoy+FYTkN0aYTQYfNrlal8H+9VnABaotwwmElSqFWBj0Mv6VIpxPuFJ/PgtQG3TpO23qBZLiW1Nq/Y4RJL8whyx3QTX7rALLBLnEsSIrrq4VcSIU9jV5JAs="

sudo: false

# Avoid rake here, as the RSpec test task spawns a new process which does not run via bundler.
script: "bundle exec rspec --format d && bundle exec rubocop"

notifications:
  slack:
    secure: bnoj7Q/2yA3gtJ2IR/YtXrWCGvN7ukHKnhg1oNYJsOYNk0oEMMgjmGnIRrcdxO4peyOid6aKlcMmP7zrOzPEJsN3qAA4UUCRGq0TgZ2RDMX1sRZ8NN/xCyt84WU9aEtTF0V1hUyG/OaQ7G65XN/XuwJGzw6VDSZE54FSdR/5/eQ=

# TODO: remove this once travis gets on with times and upgrades MySQL to 5.6.4+
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
